# Generated by Django 4.1.2 on 2022-10-12 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_aula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='foto',
        ),
    ]
